import React, { useCallback, useEffect, useState } from 'react';
import { getAlerts } from '../api/alerts';
import { Button } from '../components/common/Button';
import { Card } from '../components/common/Card';
import { EmptyState } from '../components/common/EmptyState';
import { ErrorState } from '../components/common/ErrorState';
import { LoadingState } from '../components/common/LoadingState';
import { StatusBadge } from '../components/common/StatusBadge';
import { Alert } from '../types';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [total, setTotal] = useState<number>(0);
  const [severityFilter, setSeverityFilter] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const fetchAlerts = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await getAlerts({
        severity: severityFilter || undefined,
        status: statusFilter || undefined,
        limit: 50,
      });
      setAlerts(res.items);
      setTotal(res.total);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to query alerts');
    } finally {
      setIsLoading(false);
    }
  }, [severityFilter, statusFilter]);

  useEffect(() => {
    fetchAlerts();
  }, [fetchAlerts]);

  return (
    <div style={{ padding: 'var(--space-md)', display: 'flex', flexDirection: 'column', gap: 'var(--space-md)', flex: 1 }}>
      {/* Header & Filter Controls */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 'var(--space-md)' }}>
        <div>
          <h1 style={{ fontSize: 'var(--text-lg)', textTransform: 'uppercase', letterSpacing: '0.06em', margin: 0 }}>
            Operational Alerts
          </h1>
          <p className="text-muted text-xs" style={{ margin: '2px 0 0' }}>
            System and boundary violation alerts generated by F4 rule evaluations.
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-sm)' }}>
          <select
            className="tactical-select font-mono"
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
          >
            <option value="">ALL SEVERITIES</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>

          <select
            className="tactical-select font-mono"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="">ALL STATUSES</option>
            <option value="OPEN">OPEN</option>
            <option value="ACKNOWLEDGED">ACKNOWLEDGED</option>
            <option value="RESOLVED">RESOLVED</option>
          </select>

          <Button variant="secondary" size="sm" onClick={fetchAlerts} isLoading={isLoading}>
            Refresh
          </Button>
        </div>
      </div>

      {error && <ErrorState message={error} onRetry={fetchAlerts} />}

      {/* Alerts Table */}
      <Card
        title="Alert Stream (REST Queried)"
        badge={<span className="font-mono text-xs text-muted">TOTAL: {total}</span>}
        bodyStyle={{ padding: 0 }}
      >
        {isLoading && alerts.length === 0 ? (
          <LoadingState message="Loading operational alerts..." />
        ) : alerts.length === 0 ? (
          <EmptyState title="No Alerts Found" description="No alerts match the active severity or status filters." />
        ) : (
          <div className="tactical-table-wrapper">
            <table className="tactical-table">
              <thead>
                <tr>
                  <th>Severity</th>
                  <th>Status</th>
                  <th>Alert Type</th>
                  <th>Reason / Details</th>
                  <th>Track Ref</th>
                  <th>Sensor Ref</th>
                  <th>Generated (UTC)</th>
                  <th>Resolved (UTC)</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((a) => (
                  <tr key={a.id}>
                    <td>
                      <StatusBadge status={a.severity} />
                    </td>
                    <td>
                      <StatusBadge status={a.status} />
                    </td>
                    <td className="font-mono text-xs" style={{ color: 'var(--text-secondary)' }}>
                      {a.type}
                    </td>
                    <td style={{ maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis', color: 'var(--text-primary)' }}>
                      {a.reason}
                    </td>
                    <td className="font-mono text-xs text-muted">
                      {a.track_id || 'N/A'}
                    </td>
                    <td className="font-mono text-xs text-muted">
                      {a.sensor_id || 'N/A'}
                    </td>
                    <td className="font-mono text-xs text-muted">
                      {a.created_at.substring(11, 19)}
                    </td>
                    <td className="font-mono text-xs text-muted">
                      {a.resolved_at ? a.resolved_at.substring(11, 19) : '-'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
};
