"""Pydantic API schemas."""

from app.schemas.alert import AlertPage, AlertResponse, AlertSchema
from app.schemas.analytics import (
    AlertMetrics,
    AnalyticsSummaryResponse,
    DetectionMetrics,
    ThreatMetrics,
    TrackMetrics,
)
from app.schemas.detection import DetectionSchema
from app.schemas.geofence import (
    GeofenceCreateRequest,
    GeofencePage,
    GeofenceResponse,
    GeofenceSchema,
    GeofenceUpdateRequest,
)
from app.schemas.history import (
    HistoricalAlertItem,
    HistoricalAlertsPage,
    HistoricalDetectionItem,
    HistoricalDetectionsPage,
    HistoricalThreatItem,
    HistoricalThreatsPage,
    HistoricalTrackPoint,
    HistoricalTrackStateResponse,
    TimelineEventType,
    TimelineItem,
    TimelinePage,
)
from app.schemas.ingestion import DetectionIngestionRequest, DetectionIngestionResponse, RawDetection
from app.schemas.replay import (
    ReplayComparisonReport,
    ReplayComparisonRequest,
    ReplayFilter,
    ReplayRequest,
    ReplaySnapshot,
    ReplayStepRequest,
    ReplayTrackState,
)
from app.schemas.scenario import (
    ScenarioConfiguration,
    ScenarioCreateRequest,
    ScenarioExecutionStatusResponse,
    ScenarioPage,
    ScenarioResponse,
    ScenarioSchema,
    ScenarioSensorDefinition,
    ScenarioStepRequest,
    ScenarioTargetDefinition,
    ScenarioUpdateRequest,
    ScenarioWaypoint,
)
from app.schemas.sensor import SensorResponse, SensorSchema
from app.schemas.threat import ThreatAssessmentPage, ThreatAssessmentResponse, ThreatAssessmentSchema
from app.schemas.track import TrackHistoryPage, TrackHistorySchema, TrackPage, TrackResponse, TrackSchema

__all__ = [
    "AlertMetrics",
    "AlertPage",
    "AlertResponse",
    "AlertSchema",
    "AnalyticsSummaryResponse",
    "DetectionIngestionRequest",
    "DetectionIngestionResponse",
    "DetectionMetrics",
    "DetectionSchema",
    "GeofenceCreateRequest",
    "GeofencePage",
    "GeofenceResponse",
    "GeofenceSchema",
    "GeofenceUpdateRequest",
    "HistoricalAlertItem",
    "HistoricalAlertsPage",
    "HistoricalDetectionItem",
    "HistoricalDetectionsPage",
    "HistoricalThreatItem",
    "HistoricalThreatsPage",
    "HistoricalTrackPoint",
    "HistoricalTrackStateResponse",
    "RawDetection",
    "ReplayComparisonReport",
    "ReplayComparisonRequest",
    "ReplayFilter",
    "ReplayRequest",
    "ReplaySnapshot",
    "ReplayStepRequest",
    "ReplayTrackState",
    "ScenarioConfiguration",
    "ScenarioCreateRequest",
    "ScenarioExecutionStatusResponse",
    "ScenarioPage",
    "ScenarioResponse",
    "ScenarioSchema",
    "ScenarioSensorDefinition",
    "ScenarioStepRequest",
    "ScenarioTargetDefinition",
    "ScenarioUpdateRequest",
    "ScenarioWaypoint",
    "SensorResponse",
    "SensorSchema",
    "ThreatAssessmentPage",
    "ThreatAssessmentResponse",
    "ThreatAssessmentSchema",
    "ThreatMetrics",
    "TimelineEventType",
    "TimelineItem",
    "TimelinePage",
    "TrackHistoryPage",
    "TrackHistorySchema",
    "TrackMetrics",
    "TrackPage",
    "TrackResponse",
    "TrackSchema",
]
